### ISSUE TITLE
EKF

### ISSUE THREAD

**Issue by lhfabc9** [cangzihan/strong_sort#1]
你好，我想问一下你是有实现将原本的卡尔曼滤波改成扩展卡尔曼滤波了吗？

**Comment by cangzihan** [comment]
不是的，那个EKF是我的标注问题，还是原有的卡尔曼滤波，这个工程还没做好。不好意思，这个不是那个strongsort论文的算法，我做的工程恰巧和他们同名了

**Comment by lhfabc9** [comment]
哦哦，好的，感谢回答，如果可以我想顺便问下如果要改的话原本的匀速运动模型是不是也要改啊？

**Comment by cangzihan** [comment]
具体扩展卡尔曼滤波我还不太了解，算法原本的卡尔曼实际上不是匀速运动模型，速度也是其中的一个状态量，跟踪过程中是可以改变的。但是你要修改的话，那个原本的运动方程可能会需要改

**Comment by lhfabc9** [comment]
好的，谢谢你！
